### ISSUE TITLE
Проблема при повторном подключении к чату в режиме AUTH_WITH_FORM

### ISSUE THREAD

**Issue by Sash0k** [crafttalk/crafttalk-android-sdk#11]
Воспроизводится при следующих изменениях в демо-приложении. Бэкенд ваш.

```kotlin
        Chat.init(
            this,
            getString(R.string.urlChatScheme),
            getString(R.string.urlChatHost),
            getString(R.string.urlChatNameSpace),
            authType = AuthType.AUTH_WITH_FORM, // режим авторизации
            fileProviderAuthorities = getString(R.string.chat_file_provider_authorities)
        )

Chat.wakeUp(visitor = null) // пустой visitor
```

[unauth_chat_problem.webm](https://user-images.githubusercontent.com/1607158/196303746-7e3a9ec6-cca6-4d87-8566-42e3398fdabd.webm)

**Comment by cactus666** [comment]
Это проблема связана не с формой, там от бэка в сокете приходит событие hide, что приводит к закрытию сессии.

**Comment by Sash0k** [comment]
исправлено с e9898c31b13d1e9263fed8b4379bda0ad0f602f6
