### ISSUE TITLE
Не работает передача дополнительных полей при авторизации с типом AUTH_WITH_FORM

### ISSUE THREAD

**Issue by Sash0k** [crafttalk/crafttalk-android-sdk#18]
Для режима `AUTH_WITH_FORM` используем новый метод `setNewFieldsForRegistrationVisitor` (sdk 1.2.36.+)
После первой авторизации формы поля сохраняются в SharedPreferences сдк

- с сохранением все в порядке, данные уходят в префы
- при обратной конвертации в `Visitor` они теряются, потому что парсятся только основные поля 

```kotlin
    override fun getVisitorFromSharedPreferences(): Visitor? {
        return if (pref.getBoolean(FIELD_IS_VISITOR, false)) {
            val json = pref.getString(FIELD_VISITOR, "")
            gson.fromJson(json, Visitor::class.java) 
            // допы тоже должны смапиться в addedFields
        } else {
            null
        }
    }
```

**Comment by cactus666** [comment]
Исправлено в 1.2.38.*
